#!/bin/sh
#
#
# if podman returns
#    Error: statfs /Users/xxxx/.ssh: no such file or directory
# do a
#    podman machine stop; podman machine start
#
#

echo "----------------------------------------------------------"
echo "If you see this: \"Error: statfs <home-path>/.ssh: no such file or directory\""
echo "Then run this:   podman machine stop; podman machine start"
echo "----------------------------------------------------------"

podman run --rm \
  --env PY_COLORS='1' \
  --env ANSIBLE_FORCE_COLOR='1' \
  -v ${HOME}/.ssh/:/root/.ssh/:ro \
  -v $(pwd):/data \
  docker.io/cytopia/ansible:latest-tools $@


# run the bash for checks
# podman run -t -i \
#   -v ${HOME}/.ssh/:/root/.ssh/:ro \
#   -v $(pwd):/data \
#   docker.io/cytopia/ansible:latest-tools